#include "PersistentRawFileRepository.h"

#include <cstdlib>
#include <fstream>
#include <utility>

namespace ingestion::repository
{

PersistentRawFileRepository::PersistentRawFileRepository(
    std::filesystem::path root)
{
    if (root.empty())
    {
        if (const char *env = std::getenv("RAW_STORAGE_DIR"); env && *env)
            root_ = env;
        else
            root_ = "data/uploads";
    }
    else
    {
        root_ = std::move(root);
    }
}

bool PersistentRawFileRepository::saveRawFile(
    const std::string &documentId,
    const std::string &tenantId,
    const std::string &filename,
    const std::string &fileBytes)
{
    if (documentId.empty() || tenantId.empty() || filename.empty())
        return false;

    // Do not use tenantId or filename directly as path components. The
    // document ID is generated by the server; the tenant directory is only
    // created as a storage partition after rejecting path separators.
    if (tenantId.find_first_of("/\\\\") != std::string::npos)
        return false;

    const std::filesystem::path tenantDir = root_ / tenantId;
    std::error_code ec;
    std::filesystem::create_directories(tenantDir, ec);
    if (ec)
        return false;

    const std::filesystem::path destination =
        tenantDir / (documentId + ".raw");

    std::ofstream output(destination, std::ios::binary | std::ios::trunc);
    if (!output)
        return false;

    output.write(fileBytes.data(),
                 static_cast<std::streamsize>(fileBytes.size()));
    output.flush();

    return static_cast<bool>(output);
}

bool PersistentRawFileRepository::deleteRawFile(
    const std::string &documentId,
    const std::string &tenantId)
{
    if (documentId.empty() || tenantId.empty())
        return false;
    if (tenantId.find_first_of("/\\") != std::string::npos)
        return false;

    const std::filesystem::path destination =
        root_ / tenantId / (documentId + ".raw");
    std::error_code ec;
    const bool removed = std::filesystem::remove(destination, ec);
    if (ec) return false;
    if (removed) return true;
    return !std::filesystem::exists(destination, ec) && !ec;
}

} // namespace ingestion::repository
